#!/usr/bin/env bash

# Modified from Gist:
# https://gist.github.com/LevyGuy/1f263c2303bb5b9ce44f3cfd7abdbd90

FUNCTIONS=src/functions/*.sh # Function should come first
MAIN=src/entry.sh # Primary script
OUTPUT=dist/date-tag.sh # or $2 if pass it in the params

FILES=$SOURCE
MAX_DATE=0
CHANGE=false

# stat difference between Mac and Linux
if uname | grep -q "Darwin"; then
  mod_time="-f %m"
else
  mod_time="-c %Y"
fi

FIRST_BUILD=true

# loop through all the files and compare the timestamps. if the date changed... set the flag
function get_max_date_from_folder () {
  for file in $FUNCTIONS
  do
    local TIME=$(stat $mod_time $file)
    if (( TIME > MAX_DATE )); then
      log "Detected change in $file"
      CHANGE=true
      MAX_DATE=$TIME
    fi
  done

  local MAIN_TIME=$(stat $mod_time $MAIN)
  if (( MAIN_TIME > MAX_DATE )); then
    log "Detected change in $MAIN"
    CHANGE=true
    MAX_DATE=$MAIN_TIME
  fi
}

function log () {
  if [ "$FIRST_BUILD" = false ]; then
    echo "$@"
  fi
}


function build () {
  echo "Building..."
  printf "#!/usr/bin/env bash\n\n" > $OUTPUT
  printf "# This script was generated by the build.sh script\n" >> $OUTPUT
  printf "#   Last Generated: $(date)\n\n" >> $OUTPUT
  for file in $FUNCTIONS; do
    printf "\n#######\n# $file\n#######\n" >> $OUTPUT
    cat $file >> $OUTPUT
    printf "\n#######\n# End of $file \n#######\n\n" >> $OUTPUT
  done

  printf "#######\n# $MAIN\n#######\n" >> $OUTPUT
  cat $MAIN >> $OUTPUT
  echo "Done."
}

if [ "$1" == "--watch" ]; then
  while true
  do
    get_max_date_from_folder
    if [ "$CHANGE" = true ]; then
      build
      CHANGE=false
      FIRST_BUILD=false
    fi

    sleep 2
  done
else
  build
fi